# Generated by Django 4.2 on 2023-04-21 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deadline", models.DateField()),
                ("description", models.CharField(max_length=100)),
                ("outcome", models.BooleanField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.CharField(default=uuid.uuid4, max_length=36, unique=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forecasts.forecast",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
