# Generated by Django 4.2 on 2023-04-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="title",
            field=models.CharField(default="Test", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="forecast",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
