# Generated by Django 4.2 on 2023-04-22 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forecasts", "0007_alter_forecast_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="hidden_to",
            field=models.ManyToManyField(
                blank=True, related_name="hidden_to", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="forecast",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
